configured_endpoints: 95
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/tech-with-anirudh%2Fdiscourse-sdk-78fe25cfb54d8e375a85702b2801e491e29baad55a7718ade6b11a1724ded788.yml
openapi_spec_hash: f09f4a613a109862c2fa19abde9e8c0c
config_hash: cdccc5638b0c8ccaa0f0ff8f87f0e0fc
